CREATE DATABASE QLHOCNGONNGUKYHIEU;
GO
USE QLHOCNGONNGUKYHIEU;
GO

DROP TABLE IF EXISTS BaoCaoLoi;
DROP TABLE IF EXISTS LichSuHoc;
DROP TABLE IF EXISTS KetQuaBaiHoc;
DROP TABLE IF EXISTS TienDo;
DROP TABLE IF EXISTS PhuongAnTraLoi;

DROP TABLE IF EXISTS CauHoi;
DROP TABLE IF EXISTS DangKyHoc;
DROP TABLE IF EXISTS DaPhuongTien;

DROP TABLE IF EXISTS BaiHoc_KyHieu;

DROP TABLE IF EXISTS KyHieu;
DROP TABLE IF EXISTS BaiHoc;
DROP TABLE IF EXISTS NguoiDung;
DROP TABLE IF EXISTS DanhMucBaiHoc;

DROP TABLE IF EXISTS VaiTro;
GO

CREATE TABLE VaiTro(
	Ma_VaiTro INT PRIMARY KEY IDENTITY(1,1),
	Ten_VaiTro NVARCHAR(30) NOT NULL,
	MoTa NVARCHAR(500) NOT NULL
);
GO

CREATE TABLE NguoiDung(
	Ma_NguoiDung INT PRIMARY KEY IDENTITY(1,1),
	Ho NVARCHAR(30) NOT NULL,
	Ten NVARCHAR(30) NOT NULL,
	Email NVARCHAR(30) NOT NULL,
	MatKhau NVARCHAR(50) NOT NULL,
	Ma_VaiTro INT NOT NULL,
	IsDeaf BIT NOT NULL DEFAULT 0,
	NgayLap DATETIME NOT NULL DEFAULT GETDATE(),
	SoDienThoai NVARCHAR(30),
	AnhDaiDien NVARCHAR(500),
	TrangThai NVARCHAR(30) NOT NULL DEFAULT N'HoatDong' CHECK (TrangThai IN (N'HoatDong',N'KhoaTaiKhoan',N'ChoXacNhan')),
	NgayCapNhat DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_NguoiDung_VaiTro FOREIGN KEY (Ma_VaiTro) REFERENCES VaiTro(Ma_VaiTro)
);
GO

CREATE TABLE BaiHoc(
	Ma_BaiHoc INT PRIMARY KEY IDENTITY(1,1),
	TieuDe NVARCHAR(200) NOT NULL,
	MoTa NVARCHAR(500),
	CapDo NVARCHAR(20) NOT NULL CHECK(CapDo IN ('Beginner','Intermediate','Advance')),
	Ma_NguoiTao INT NOT NULL,
	NgayTaoBai DATETIME NOT NULL DEFAULT GETDATE(),
	TrangThai NVARCHAR(30) NOT NULL DEFAULT N'NhapBai' CHECK (TrangThai IN (N'NhapBai', N'DaXuatBan',N'TamAn')),
	ThuTu INT NOT NULL DEFAULT 1,
	ThoiLuongDuKien INT,
	AnhDaiDien NVARCHAR(500),
	CONSTRAINT FK_BaiHoc_NguoiDung FOREIGN KEY (Ma_NguoiTao) REFERENCES NguoiDung(Ma_NguoiDung)
);
GO

CREATE TABLE KyHieu(
	Ma_KyHieu INT PRIMARY KEY IDENTITY(1,1),
	TuVung NVARCHAR(100) NOT NULL,
	MoTa NVARCHAR(500),
	TrangThai NVARCHAR(30) NOT NULL DEFAULT N'HoatDong' CHECK (TrangThai IN (N'HoatDong',N'KhongHoatDong')),
	ThuTuHienThi INT NOT NULL DEFAULT 1,
	DoKho NVARCHAR(20) NOT NULL DEFAULT N'De' CHECK (DoKho IN(N'De',N'TrungBinh',N'Kho'))
);
GO

CREATE TABLE BaiHoc_KyHieu(
	Ma_BaiHoc INT NOT NULL,
	Ma_KyHieu INT NOT NULL,
	ThuTu INT NOT NULL DEFAULT 1,
	CONSTRAINT PK_BaiHoc_KyHieu PRIMARY KEY (Ma_BaiHoc,Ma_KyHieu),
	CONSTRAINT FK_BHKH_BaiHoc FOREIGN KEY (Ma_BaiHoc) REFERENCES BaiHoc(Ma_BaiHoc),
	CONSTRAINT FK_BHKH_KyHieu FOREIGN KEY (Ma_KyHieu) REFERENCES KyHieu(Ma_KyHieu)
);
GO

CREATE TABLE DaPhuongTien(
	Ma_DaPhuongTien INT PRIMARY KEY IDENTITY(1,1),
	Ma_KyHieu INT NOT NULL,
	LoaiTep NVARCHAR(30) NOT NULL CHECK(LoaiTep IN ('Video','Anh')),
	LaChinh BIT NOT NULL DEFAULT 0,
	NgayTaiLen DATETIME NOT NULL DEFAULT GETDATE(),
	DuongDanTep NVARCHAR(30) NOT NULL,
	TenTep NVARCHAR(30) NOT NULL,
	MoTa NVARCHAR(500),
	ThoiLuong INT,
	KichThuocTep BIGINT NOT NULL,
	CONSTRAINT FK_DaPhuongTien_KyHieu FOREIGN KEY (Ma_KyHieu) REFERENCES KyHieu(Ma_KyHieu)
);
GO

CREATE TABLE DangKyHoc(
	Ma_DangKy INT PRIMARY KEY IDENTITY(1,1),
	Ma_NguoiDung INT NOT NULL,
	Ma_BaiHoc INT NOT NULL,
	NgayDangKy DATETIME NOT NULL DEFAULT GETDATE(),
	TrangThaiHoc NVARCHAR(30) NOT NULL DEFAULT N'ChuaBatDau' CHECK (TrangThaiHoc IN (N'ChuaBatDau',N'DangHoc',N'HoanThanh')),
	NgayHoanThanh DATETIME,
	PhanTramHoanThanh FLOAT NOT NULL DEFAULT 0 CHECK (PhanTramHoanThanh BETWEEN 0 AND 100),
	CONSTRAINT FK_DangKyHoc_NguoiDung FOREIGN KEY (Ma_NguoiDung) REFERENCES NguoiDung(Ma_NguoiDung),
	CONSTRAINT FK_DangKyHoc_BaiHoc FOREIGN KEY (Ma_BaiHoc) REFERENCES BaiHoc(Ma_BaiHoc),
	CONSTRAINT UNQ_DangKy UNIQUE (Ma_NguoiDung,Ma_BaiHoc)
);
GO

CREATE TABLE CauHoi(
	Ma_CauHoi INT PRIMARY KEY IDENTITY(1,1),
	Ma_BaiHoc INT NOT NULL,
	NoiDungCauHoi NVARCHAR(100) NOT NULL,
	Ma_KyHieuDung INT NOT NULL,
	LoaiCauHoi NVARCHAR(30) NOT NULL DEFAULT N'TracNghiem' CHECK( LoaiCauHoi IN (N'TracNghiem',N'DienKhuyet',N'NhanBiet')),
	DiemMacDinh FLOAT NOT NULL DEFAULT 10,
	GiaiThich NVARCHAR(300),
	CONSTRAINT FK_CauHoi_BaiHoc FOREIGN KEY (Ma_BaiHoc) REFERENCES BaiHoc(Ma_BaiHoc),
	CONSTRAINT FL_CauHoi_KyHieu FOREIGN KEY (Ma_KyHieuDung) REFERENCES KyHieu(Ma_KyHieu)
);
GO

CREATE TABLE TienDo(
	Ma_TienDo INT PRIMARY KEY IDENTITY(1,1),
	Ma_NguoiDung INT NOT NULL,
	Ma_CauHoi INT NOT NULL,
	DapAnDung BIT NOT NULL DEFAULT 0,
	DiemSo FLOAT NOT NULL DEFAULT 0,
	ThoiDiemThucHien DATETIME NOT NULL DEFAULT GETDATE(),
	SoLanThu INT NOT NULL DEFAULT 1,
	ThoiGianLam INT NOT NULL DEFAULT 0,
	TrangThai NVARCHAR(30) NOT NULL DEFAULT N'HoanThanh' CHECK (TrangThai IN(N'HoanThanh',N'ChuaDat',N'DangLam')),	
	CONSTRAINT FK_TienDo_NguoiDung FOREIGN KEY (Ma_NguoiDung) REFERENCES NguoiDung(Ma_NguoiDung),
	CONSTRAINT FK_TienDo_CauHoi FOREIGN KEY (Ma_CauHoi) REFERENCES CauHoi(Ma_CauHoi)
);
GO

CREATE TABLE DanhMucBaiHoc(
	Ma_DanhMuc INT PRIMARY KEY IDENTITY(1,1),
	Ten_DanhMuc NVARCHAR(100) NOT NULL,
	MoTa NVARCHAR(300),
	TrangThai NVARCHAR(30) NOT NULL DEFAULT N'HoatDong' CHECK (TrangThai IN(N'HoatDong',N'KhongHoatDong')),
);
GO

CREATE TABLE PhuongAnTraLoi(
	Ma_PhuongAn INT PRIMARY KEY IDENTITY(1,1),
	Ma_CauHoi INT,
	NoiDung NVARCHAR(500) NOT NULL,
	LaDapAnDung BIT NOT NULL DEFAULT 0,
	ThuTu INT NOT NULL DEFAULT 1,
	CONSTRAINT FK_PhuongAnTraLoi_CauHoi FOREIGN KEY (Ma_CauHoi) REFERENCES CauHoi(Ma_CauHoi)
);
GO

CREATE TABLE KetQuaBaiHoc(
	Ma_KetQua INT PRIMARY KEY IDENTITY(1,1),
	Ma_NguoiDung INT NOT NULL,
	Ma_BaiHoc INT NOT NULL,
	DiemTong FLOAT NOT NULL DEFAULT 0,
	PhanTramDung FLOAT NOT NULL DEFAULT 0 CHECK (PhanTramDung BETWEEN 0 AND 100),
	NgayHoanThanh DATETIME,
	TrangThai NVARCHAR(20) NOT NULL DEFAULT N'Dat' CHECK (TrangThai IN(N'Dat',N'KhongDat')),
	CONSTRAINT FK_KetQuaBaiHoc_NguoiDung FOREIGN KEY (Ma_NguoiDung) REFERENCES NguoiDung(Ma_NguoiDung),
	CONSTRAINT FK_KetQuaBaiHoc_BaiHoc FOREIGN KEY (Ma_BaiHoc) REFERENCES BaiHoc(Ma_BaiHoc)
);
GO

CREATE TABLE LichSuHoc(
	Ma_LichSu INT PRIMARY KEY IDENTITY(1,1),
	Ma_NguoiDung INT NOT NULL,
	Ma_BaiHoc INT NOT NULL,
	ThoiGianBatDau DATETIME NOT NULL DEFAULT GETDATE(),
	ThoiGianKetThuc DATETIME NOT NULL,
	GhiChu NVARCHAR(500) NOT NULL,
	CONSTRAINT FK_LichSuHoc_NguoiDung FOREIGN KEY (Ma_NguoiDung) REFERENCES NguoiDung(Ma_NguoiDung),
	CONSTRAINT FK_LichSuHoc_BaiHoc FOREIGN KEY (Ma_BaiHoc) REFERENCES BaiHoc(Ma_BaiHoc)
);
GO

CREATE TABLE BaoCaoLoi(
	Ma_BaoCao INT PRIMARY KEY IDENTITY(1,1),
	Ma_KyHieu INT NOT NULL,
	Ma_NguoiDung INT NOT NULL,
	NoiDungLoi NVARCHAR(500) NOT NULL,
	NgayBaoCao DATETIME NOT NULL DEFAULT GETDATE(),
	TrangThai NVARCHAR(30) NOT NULL DEFAULT N'DaXuLy' CHECK(TrangThai IN(N'DaXuLy',N'ChuaXuLy',N'DangXuLy')),
	CONSTRAINT FK_BaoCaoLoi_KyHieu FOREIGN KEY (Ma_KyHieu) REFERENCES KyHieu(Ma_KyHieu),
	CONSTRAINT FK_BaoCaoLoi_NguoiDung FOREIGN KEY (Ma_NguoiDung) REFERENCES NguoiDung(Ma_NguoiDung)
);
GO